---
- name: Install Zabbix agent
  hosts: all
  become: yes
  debugger: on_failed
  tasks:

    - name: Install zabbix-release CentOS 7
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Install zabbix release Ubuntu
      apt:
        deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bfocal_all.deb
      when: ansible_distribution == 'Ubuntu'

    - name: Install zabbix-agent package
      package:
        name: zabbix-agent
        state: present

    - name: Change Server IP
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        line: "Server=192.168.1.23"

        #    - name: Change Active Server IP
        #      lineinfile:
        #        path: /etc/zabbix/zabbix_agentd.conf
        #        regexp: 'ServerActive=127.0.0.1'
        #        line: "ServerActive=127.0.0.1,192.168.1.23"

    - name: Change hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Hostname=Zabbix server'
        line: Hostname={{ ansible_hostname }}

    - name: Stop zabbix-agent
      service:
        name: zabbix-agent
        state: stopped
        enabled: no
      ignore_errors: yes


    - name: Start zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes
